site_name: 示奇の陋室
site_url: 
site_author: 示奇
nav:
  - Home:
    - index.md
    - begin/myself.md
    - begin/website_introduction.md
  - Blog:
    - blog/blog_1.md
  - Novel:
    - novel/zhi_zi.md
  - Other:
    - other/jiang.md
theme:
  language: zh
  font:
   text: LXGW WenKai Mono TC
   code: Roboto Mono
  name: material #主题
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - search.suggest
    - search.share
  palette:
  - scheme: default
    primary: blue grey
    accent: light green
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: grey
    accent: orange
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  plugins:
    - search
    - tags
    - blog:
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Holidays
        - News