site_name: FuSyuan的小屋
site_url: 
site_author: FuSyuan
theme:
  name: material
  language: en
  font:
    text: Roboto Slab
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: lime
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
